# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2b835df7bef2eb4406d546a2c4df48c1b9eb15cecbb961591f56fd1b21b1aaac141b7d82fa6f05a2447265cbf71cbbc5d39395adc020a3cd067a664f6a94003

test:
  secret_key_base: 1ff88a16da950411ecbde47cc6af644ba14b149858037929b23374dddfc84e4758387baf701b7fb197722ececb347cba0cfbd1a17cb8ec0f4634bcfa898d47a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
